---
name: linux
run-name: Linux Workflow
"on": [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Container Registry Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Project
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/theomund/arcturus/development
          cacheFrom: ghcr.io/theomund/arcturus/development
          push: always
          runCmd: just build
